name: spatial-transcriptomics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scanpy
  - cell2location
  - stardist
  - tifffile
  - geopandas
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scvi-colab
  - pip:
    - scvi
